
final List<String> locations = [
  'Mohammadpur Dhaka',
  'Dhanmondi Dhaka',
  'Block H Bashundhara R-A Dhaka',
  'Mirpur Dhaka',
  'Lalmatia Dhaka',
  'Farmgate Tejgaon Dhaka',
  'Block B Nobodoy Housing Society Mohammadpur Dhaka',
  'Gulshan 1 Gulshan Dhaka',
  'Baridhara Dhaka',
  'Bashundhara R-A Dhaka',
  'PC Culture Housing Mohammadpur Dhaka',
  'Jigatola Hazaribag Dhaka',
  'West Kazipara Mirpur Dhaka',
  'Block D Bashundhara R-A Dhaka',
  'Block J Bashundhara R-A Dhaka',
  'Nikunja 2 Nikunja Dhaka',
  'Sector 6 Uttara Dhaka',
  'Khilgaon Dhaka',
  'Block K Baridhara Dhaka',
  'Ibrahimpur Dhaka',
  'Sector 5 Uttara Dhaka',
  'Nurer Chala Badda Dhaka',
  'Block F Bashundhara R-A Dhaka',
  'Sector 4 Uttara Dhaka',
  'Rajabazar Tejgaon Dhaka',
  'Sector 9 Uttara Dhaka',
  'Sector 14 Uttara Dhaka',
  'Block D Section 12 Mirpur Dhaka',
  'Block G Bashundhara R-A Dhaka',
  'Baitul Aman Housing Society Adabor Dhaka',
  'Sector 11 Uttara Dhaka',
  'Sector 7 Uttara Dhaka',
  'Gulshan 2  Gulshan  Dhaka',
  'Sector 10 Uttara Dhaka',
  'Block A  Sat Masjid Housing Mohammadpur Dhaka',
  'Banani Dhaka',
  'Block A Bashundhara R-A Dhaka',
  'Kakrail Dhaka',
  'Block I Bashundhara R-A Dhaka',
  'Malibagh Dhaka',
  'West Dhanmondi and Shangkar Dhanmondi Dhaka',
  'Maghbazar Dhaka',
  'West Kalachandpur Kalachandpur Dhaka',
  'Sector 3 Uttara Dhaka',
  'Badda Dhaka',
  'Block K Bashundhara R-A Dhaka',
  'East Badda Badda Dhaka',
  'Kamal Sarani South Pirerbag Pirerbag Mirpur Dhaka',
  'Block A Niketan Dhaka',
  'East Goran Goran Khilgaon Dhaka',
  'Block C Section 13 Mirpur Dhaka',
  'Block B Bashundhara R-A Dhaka',
  'New Eskaton Eskaton Dhaka',
  'Block C Bashundhara R-A Dhaka',
  'Block H Banasree Dhaka',
  'Middle Monipur Mirpur Dhaka',
  'Monipuripara Tejgaon Dhaka',
  'Shantibag Malibagh Dhaka',
  'Block F aziz Moholla Mohammadpur Dhaka',
  'East Bashabo Bashabo Dhaka',
  'Block A Kaderabad Housing Society Bosila Mohammadpur Dhaka',
  'Baridhara DOHS Dhaka',
  'Sector 13 Uttara Dhaka',
  'Mohammadi Housing LTD. Mohammadpur Dhaka',
  'Tejgaon Dhaka',
  'Sector 12 Uttara Dhaka',
  'Dhaka Real Estate Katashur Mohammadpur Dhaka',
  'Block A Chandrima Model Town Mohammadpur Dhaka',
  'Block A Section 11 Mirpur Dhaka',
  'Middle Pirerbag Pirerbag Mirpur Dhaka',
  'Block A Banasree Dhaka',
  'Block C Aftab Nagar Dhaka',
  'Block D Section 2 Mirpur Dhaka',
  'West Shewrapara Mirpur Dhaka',
  'Block C Section 2 Mirpur Dhaka',
  'Middle Paikpara Mirpur Dhaka',
  'Taltola Khilgaon Dhaka',
  'South Monipur Mirpur Dhaka',
  'Pirerbag Mirpur Dhaka',
  'Eskaton Dhaka',
  '1st Colony Mirpur Dhaka',
  'Uttar Badda Badda Dhaka',
  'Chandmiya Housing Mohammadpur Dhaka',
  'East Merul Badda Merul Badda Badda Dhaka',
  'Avenue 3 Mirpur DOHS Mirpur Dhaka',
  'Faydabad Dakshin Khan Dhaka',
  'Sector 1 Block F Aftab Nagar Dhaka',
  'Sector 2 Block F Aftab Nagar Dhaka',
  'Section 2 Mirpur Dhaka',
  'Block C Kaderabad Housing Society Bosila Mohammadpur Dhaka',
  'Mohammadia Housing Society Mohammadpur Dhaka',
  'Block D Mansurabad Housing Society Adabor Dhaka',
  'Mohakhali DOHS Dhaka',
  'Sector 1 Uttara Dhaka',
  'Block J Baridhara Dhaka',
  'Kallyanpur Mirpur Dhaka',
  'Shyamoli Housing Shekhertek Mohammadpur Dhaka',
  'Wari Sutrapur Dhaka',
  'Hatirpool Dhaka',
  'South Pirerbag Pirerbag Mirpur Dhaka',
  'Taltola Agargaon Dhaka',
  'Gawair Dakshin Khan Dhaka',
  'Mollika R/A Section 7 Mirpur Dhaka',
  'Gulbag Malibagh Dhaka',
  'Tejkunipara Tejgaon Dhaka',
  'Block C Nobodoy Housing Society Mohammadpur Dhaka',
  'Pallabi Extension Pallabi Mirpur Dhaka',
  'Modhubag Boro Maghbazar Maghbazar Dhaka',
  'Block L Bashundhara R-A Dhaka',
  'Avenue 1 Mirpur DOHS Mirpur Dhaka',
  'Cantonment Dhaka',
  'Banasree Dhaka',
  'Block E Banasree Dhaka',
  'Khilkhet Dhaka',
  'Block A Nobodoy Housing Society Mohammadpur Dhaka',
  'Uttara Dhaka',
  'Block A Chad Uddan Housing Mohammadpur Dhaka',
  'Block B Aftab Nagar Dhaka',
  'Section 12 Mirpur Dhaka',
  'Section 10 Mirpur Dhaka',
  'Dakkhin Paikpara Paikpara Mirpur Dhaka',
  'Naya Paltan Motijheel Dhaka',
  'Tikatuli Sutrapur Dhaka',
  'Shantinagar Dhaka',
  'Shegunbagicha Dhaka',
  'Motijheel Dhaka',
  'Block A Rajuk Uttara Apartment Project Sector 18 Uttara Dhaka',
  'Block B Banasree Dhaka',
  'Goran Khilgaon Dhaka',
  'East Shewrapara Mirpur Dhaka',
  'Block D Mohanagar Housing West Rampura Rampura Dhaka',
  'Block F Section 11 Mirpur Dhaka',
  'Kathalbagan Dhaka',
  'Merul Badda Badda Dhaka',
  'Tilpapara Khilgaon Dhaka',
  'Kalachandpur Dhaka',
  'Senpara Parbata Section 10 Mirpur Dhaka',
  'East Rampura Rampura Dhaka',
  'South Banasree Project Banasree Dhaka',
  'Section 1 Mirpur Dhaka',
  'North Pirerbag Pirerbag Mirpur Dhaka',
  'RK Mission Road Gopibag Motijheel Dhaka',
  'Avenue 6 Mirpur DOHS Mirpur Dhaka',
  'Shyamoli Dhaka',
  'Kalabagan Dhaka',
  'Hazaribag Dhaka',
  'Avenue 2 Mirpur DOHS Mirpur Dhaka',
  'Priyanka City Sector 12 Uttara Dhaka',
  'Kuril Dhaka',
  'Gandaria Sutrapur Dhaka',
  'Pallabi Mirpur Dhaka',
  'Avenue 4 Mirpur DOHS Mirpur Dhaka',
  'Boro Maghbazar Maghbazar Dhaka',
  'Rampura Dhaka',
  'Agargaon Dhaka',
  'Block F Banasree Dhaka',
  'Dakshin Khan Dhaka',
  'Comfort Housing Adabor Dhaka',
  'Avenue 5 Block C Section 11 Mirpur Dhaka',
  'Mohakhali Dhaka',
  'Block M South Banasree Project Banasree Dhaka',
  'Block E Section 2 Mirpur Dhaka',
  'Block B Section 12 Mirpur Dhaka',
  'Block J Banasree Dhaka',
  'Mirpur DOHS Mirpur Dhaka',
  'New Market Dhaka',
  'Madhya Ajampur Dakshin Khan Dhaka',
  'Kafrul Dhaka',
  'Ullan West Rampura Rampura Dhaka',
  'South Chalabon Dakshin Khan Dhaka',
  'Kachukhet Dhaka',
  'Azimpur Lalbagh Dhaka',
  'Block E Bashundhara R-A Dhaka',
  'Shukrabad Dhanmondi Dhaka',
  'Block C Bochila City Developers Ltd Bochila Mohammadpur Dhaka',
  'Kaderabad Housing Society Katashur Mohammadpur Dhaka',
  'Amligola Lalbagh Dhaka',
  'Meradia Khilgaon Dhaka',
  'Block B Mansurabad Housing Society Adabor Dhaka',
  'Block A Aftab Nagar Dhaka',
  'Block G Section 1 Mirpur Dhaka',
  'Mollartek Dakshin Khan Dhaka',
  'Shahjadpur Badda Dhaka',
  'Block C Section 12 Mirpur Dhaka',
  'Block D Section 11 Mirpur Dhaka',
  'Block D South Banasree Project Banasree Dhaka',
  'Block B South Banasree Project Banasree Dhaka',
  'Manikdi Cantonment Dhaka',
  'Block A Section 10 Mirpur Dhaka',
  'West Monipur Mirpur Dhaka',
  'Middle Badda Badda Dhaka',
  'East Kazipara Mirpur Dhaka',
  'Section 7 Mirpur Dhaka',
  'South Goran Goran Khilgaon Dhaka',
  'Tajmahal Road Mohammadpur Dhaka',
  'Block F Section 2 Mirpur Dhaka',
  'Block B Section 11 Mirpur Dhaka',
  'Kadamtala Bashabo Dhaka',
  'Block D Section 10 Mirpur Dhaka',
  'West Rampura Rampura Dhaka',
  'Block E Section 12 Mirpur Dhaka',
  'Paikpara Ahmed Nagar Mirpur Dhaka',
  'Nadda Dhaka',
  'Chowdhuripara Khilgaon Dhaka',
  'Block D Eastern Housing Pallabi Mirpur Dhaka',
  'Sector 2 Block H Aftab Nagar Dhaka',
  'Ullan Rampura Dhaka',
  'Baigertek Cantonment Dhaka',
  'Road No 10 Block C Section 11 Mirpur Dhaka',
  'Block Dha Section 12 Mirpur Dhaka',
  'Banani DOHS Dhaka',
  'Block E Kaderabad Housing Society Bosila Mohammadpur Dhaka',
  'Block G South Banasree Project Banasree Dhaka',
  'Block L Eastern Housing Pallabi Mirpur Dhaka',
  'Old Eskaton Eskaton Dhaka',
  'West Nakhalpara Tejgaon Dhaka',
  'Shiddheswari Dhaka',
  'Block B Dolipara Uttara Dhaka',
  'Malibagh Chowdhury Para Malibagh Dhaka',
  'South Badda Badda Dhaka',
  'Rajarbagh Motijheel Dhaka',
  'Block C Dhaka Uddan Mohammadpur Dhaka',
  'Joar Sahara Dhaka',
  'Block B Section 13 Mirpur Dhaka',
  'Block A Section 12 Mirpur Dhaka',
  'Ashkona Dakshin Khan Dhaka',
  'Katashur Mohammadpur Dhaka',
  'Adabor Dhaka',
  'Rayer Bazaar Hazaribag Dhaka',
  'Block G Banasree Dhaka',
  'Block L South Banasree Project Banasree Dhaka',
  'Mastertek Cantonment Dhaka',
  'North Kamlapur Kamlapur Motijheel Dhaka',
  'Rupnagar R/A Mirpur Dhaka',
  'Rupnagar R/A Mirpur Dhaka',
  'Block D Nobodoy Housing Society Mohammadpur Dhaka',
  'Block D Chandrima Model Town Mohammadpur Dhaka',
  'Suchona Model Town Bochila Mohammadpur Dhaka',
  'Block A Bochila City Developers Ltd Bochila Mohammadpur Dhaka',
  'North Ibrahimpur Ibrahimpur Dhaka',
  'Shah Ali Bag Section 1 Mirpur Dhaka',
  'Block F Eastern Housing Pallabi Mirpur Dhaka',
  'Sector 1 Block G Aftab Nagar Dhaka',
  'North Jatra Bari Jatra Bari Dhaka',
  'West Kafrul Taltola Agargaon Dhaka',
  'Block A Bochila Garden City Bochila Mohammadpur Dhaka',
  'Lake View Society South Pirerbag Pirerbag Mirpur Dhaka',
  'Sector 1 Block E Aftab Nagar Dhaka',
  'Block C Mansurabad Housing Society Adabor Dhaka',
  'Block D Dhaka Uddan Mohammadpur Dhaka',
  'North Shahjahanpur Dhaka',
  'Block B Chandrima Model Town Mohammadpur Dhaka',
  'East Monipur Mirpur Dhaka',
  'Block C Khilgaon Dhaka',
  'South Mollartek Dakshin Khan Dhaka',
  'West Mollartek Dakshin Khan Dhaka',
  'Block A Dhaka Uddan Mohammadpur Dhaka',
  'Jahuri Moholla Mohammadpur Dhaka',
  'Arambagh Motijheel Dhaka',
  'Shyamoli Housing (2nd Project) Adabor Dhaka',
  'Nabi Nagar Housing Mohammadpur Dhaka',
  'Dhaka Uddan Mohammadpur Dhaka',
  'Bochila Garden City Bochila Mohammadpur Dhaka',
  'Block C Banasree Dhaka',
  'Avenue 3 Block B Section 11 Mirpur Dhaka',
  'North Azampur Dakshin Khan Dhaka',
  'Moushair Dakshin Khan Dhaka',
  'Block E South Banasree Project Banasree Dhaka',
  'Block F South Banasree Project Banasree Dhaka',
  'South Kallyanpur Kallyanpur Mirpur Dhaka',
  'Zafrabad Hazaribag Dhaka',
  'Bochila Mohammadpur Dhaka',
  'Block C Section 10 Mirpur Dhaka',
  'Sobhanbagh Tejgaon Dhaka',
  'East Nakhalpara Tejgaon Dhaka',
  'Avenue 11 Mirpur DOHS Mirpur Dhaka',
  'Matikata Cantonment Dhaka',
  '2nd Colony Mirpur Dhaka',
  'Block B Dhaka Uddan Mohammadpur Dhaka',
  'Vashantek Cantonment Dhaka',
  'Janata Housing Sher- E- Banglanagar West Agargaon Agargaon Dhaka',
  'Dakkhin Paikpara Mirpur Dhaka',
  'Natun Bazar Badda Dhaka',
  'Lalbagh Dhaka',
  'Bonolota Abashik Elaka West Agargaon Agargaon Dhaka',
  'Road No 11 Block C Section 11 Mirpur Dhaka',
  'Block D Section 15 Mirpur Dhaka',
  'Block B Section 1 Mirpur Dhaka',
  'Mazar Road 2nd Colony Mirpur Dhaka',
  'Janata Housing Shah Ali Bag Section 1 Mirpur Dhaka',
  'West Agargaon Agargaon Dhaka',
  'Tali office Road Hazaribag Dhaka',
  'Block B Bochila City Developers Ltd Bochila Mohammadpur Dhaka',
  'Block E Section 1 Mirpur Dhaka',
  'Block B Bochila West Dhanmondi R/A Bochila Mohammadpur Dhaka',
  'Block C Eastern Housing Pallabi Mirpur Dhaka',
  'Block A Section 1 Mirpur Dhaka',
  'Block A Sayednagar East Vatara Vatara Badda Dhaka',
  'Block E Eastern Housing Pallabi Mirpur Dhaka',
  'Block D Pallabi Mirpur Dhaka',
  'Vatara Badda Dhaka',
  'South Manikdi Manikdi Cantonment Dhaka',
  'Middle Bashabo Bashabo Dhaka',
  'Block C Chandrima Model Town Mohammadpur Dhaka',
  'North Goran Goran Khilgaon Dhaka',
  'Hashem Khan Road Sultanganj Rayer Bazaar Hazaribag Dhaka',
  'Sonatangar Jigatola Hazaribag Dhaka',
  'Boshoty Housing Borobag Section 2 Mirpur Dhaka',
  'Swapnodhara Housing Bochila Mohammadpur Dhaka',
  'Sikder Real Estate Tali office Road Hazaribag Dhaka',
  'Fakirapool Motijheel Dhaka',
  'North Bashabo Bashabo Dhaka',
  'Block E Arambag Residential Area Pallabi Mirpur Dhaka',
  'Shahidbag Malibagh Dhaka',
  'Block C Arambag Residential Area Pallabi Mirpur Dhaka',
  'Bashabo Dhaka',
  'Shahjahanpur Dhaka',
  'Purana Paltan Motijheel Dhaka',
  'Ahmed Nagar Mirpur Dhaka',
  'Kamlapur Motijheel Dhaka',
  'Block G/1 Section 2 Mirpur Dhaka',
  'Eastern Pallabi Pallabi Mirpur Dhaka',
  'Sector 1 Block D Aftab Nagar Dhaka',
  'Block B Section 10 Mirpur Dhaka',
  'Kadamtala Road Kadamtala Bashabo Dhaka',
  'Bagan Bari Cantonment Dhaka',
  'aziz Moholla Mohammadpur Dhaka',
  'Block D Kaderabad Housing Society Bosila Mohammadpur Dhaka',
  'South Madartek Madartek Bashabo Dhaka',
  'Kawlar Dakshin Khan Dhaka',
  'South Azampur Dakshin Khan Dhaka',
  'Bosila Mohammadpur Dhaka',
  'Block C Chad Uddan Housing Mohammadpur Dhaka',
  'Block B Chad Uddan Housing Mohammadpur Dhaka',
  'Block D Dakkhin Paikpara Paikpara Mirpur Dhaka',
  'Block D Banasree Dhaka',
  'Block H Section 2 Mirpur Dhaka',
  'Paikpara Mirpur Dhaka',
  'Aainusbag Dakshin Khan Dhaka',
  'Block C Section 6 Mirpur Dhaka',
  'Narinda Sutrapur Dhaka',
  'Khilbari Tek Badda Dhaka',
  'Block D Bochila Garden City Bochila Mohammadpur Dhaka',
  'Jagannathpur Badda Dhaka',
  'Adarsha Para Uttar Khan Dhaka',
  'Tallabag Hazaribag Dhaka',
  'Shantipur South Goran Goran Khilgaon Dhaka',
  'Block B Section 6 Mirpur Dhaka',
  'Sector 2 Block D Aftab Nagar Dhaka',
  'Block J Pallabi Extension Pallabi Mirpur Dhaka',
  'Block D Section 1 Mirpur Dhaka',
  'Block A Bochila West Dhanmondi R/A Bochila Mohammadpur Dhaka',
  'Janata Housing Society Adabor Dhaka',
  'Section 13 Mirpur Dhaka',
  'Block A Section 13 Mirpur Dhaka',
  'Turag City Section 1 Mirpur Dhaka',
  'Block D Section 6 Mirpur Dhaka',
  'East Hazipara East Rampura Rampura Dhaka',
  'Darussalam Mirpur Dhaka',
  'West Dhanmondi Dhanmondi Dhaka',
  'Road No 12 Block B Section 11 Mirpur Dhaka',
  'Abdullahbag Uttar Badda Badda Dhaka',
  'Bangshal Dhaka',
  'Block B Pallabi Mirpur Dhaka',
  'Jamtola Kawlar Dakshin Khan Dhaka',
  'Abdur Rafique Housing Society Shekhertek Mohammadpur Dhaka',
  'Ali And Nur Real Estate Mohammadpur Dhaka',
  'Sayednagar East Vatara Vatara Badda Dhaka',
  'Block TA Section 6 Mirpur Dhaka',
  'Chalabon Dakshin Khan Dhaka',
  'Block B Future Town Bochila Mohammadpur Dhaka',
  'Sutrapur Dhaka',
  'Chairman Para Dakshin Khan Dhaka',
  'South Bishil Section 1 Mirpur Dhaka',
  'PC Culture Housing Society Shyamoli Dhaka',
  'Block B Sayednagar East Vatara Vatara Badda Dhaka',
  'East Azampur Dakshin Khan Dhaka',
  '3rd Colony Mirpur Dhaka',
  'Block C Bochila Garden City Bochila Mohammadpur Dhaka',
  'Avenue 2 Block A Section 11 Mirpur Dhaka',
  'Moddhopara Ashkona Dakshin Khan Dhaka',
  'Lalkuthi 3rd Colony Mirpur Dhaka',
  'East Mollartek Dakshin Khan Dhaka',
  'Block E Chandrima Model Town Mohammadpur Dhaka',
  'Block H South Banasree Project Banasree Dhaka',
  'Block B Metro Housing Bochila Mohammadpur Dhaka',
  'Block A Metro Housing Bochila Mohammadpur Dhaka',
  'Block B Eastern Housing Pallabi Mirpur Dhaka',
  'Anurbag Dakshin Khan Dhaka',
  'Block C Future Town Bochila Mohammadpur Dhaka',
  'Barontek Cantonment Dhaka',
  'South Bashabo Bashabo Dhaka',
  'Sabujbag South Bashabo Bashabo Dhaka',
  'Taltola Dakshin Khan Dhaka',
  'Block C Chandmiya Housing Mohammadpur Dhaka',
  'Section 11 Mirpur Dhaka',
  'West Vatara Vatara Badda Dhaka',
  'Avenue 10 Mirpur DOHS Mirpur Dhaka',
  'Naya Nagar Vatara Badda Dhaka',
  'Sector 15 Uttara Dhaka',
  'Avenue 7 Mirpur DOHS Mirpur Dhaka',
  'Rajarbag Bashabo Dhaka',
  'Kazibari Dakshin Khan Dhaka',
  'Kuratoli Kuril Dhaka',
  'Block E Section 11 Mirpur Dhaka',
  'Block J Section 3 Mirpur Dhaka',
  'Block B Dakkhin Paikpara Paikpara Mirpur Dhaka',
  'West Dolairpar Shyampur Dhaka',
  'Block C Section 11 Mirpur Dhaka',
  'Block C1 Sector 15 Uttara Dhaka',
];